#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-quantmod
Version  : 0.4.13
Release  : 28
URL      : https://cran.r-project.org/src/contrib/quantmod_0.4-13.tar.gz
Source0  : https://cran.r-project.org/src/contrib/quantmod_0.4-13.tar.gz
Summary  : Quantitative Financial Modelling Framework
Group    : Development/Tools
License  : GPL-3.0
Requires: R-TTR
Requires: R-curl
Requires: R-xts
BuildRequires : R-TTR
BuildRequires : R-curl
BuildRequires : R-xts
BuildRequires : clr-R-helpers

%description
No detailed description available

%prep
%setup -q -c -n quantmod

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1524276082

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1524276082
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library quantmod
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library quantmod
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library quantmod
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/quantmod/DESCRIPTION
/usr/lib64/R/library/quantmod/INDEX
/usr/lib64/R/library/quantmod/Meta/Rd.rds
/usr/lib64/R/library/quantmod/Meta/demo.rds
/usr/lib64/R/library/quantmod/Meta/features.rds
/usr/lib64/R/library/quantmod/Meta/hsearch.rds
/usr/lib64/R/library/quantmod/Meta/links.rds
/usr/lib64/R/library/quantmod/Meta/nsInfo.rds
/usr/lib64/R/library/quantmod/Meta/package.rds
/usr/lib64/R/library/quantmod/NAMESPACE
/usr/lib64/R/library/quantmod/NEWS.md
/usr/lib64/R/library/quantmod/R/quantmod
/usr/lib64/R/library/quantmod/R/quantmod.rdb
/usr/lib64/R/library/quantmod/R/quantmod.rdx
/usr/lib64/R/library/quantmod/demo/chartSeries.R
/usr/lib64/R/library/quantmod/help/AnIndex
/usr/lib64/R/library/quantmod/help/aliases.rds
/usr/lib64/R/library/quantmod/help/paths.rds
/usr/lib64/R/library/quantmod/help/quantmod.rdb
/usr/lib64/R/library/quantmod/help/quantmod.rdx
/usr/lib64/R/library/quantmod/html/00Index.html
/usr/lib64/R/library/quantmod/html/R.css
/usr/lib64/R/library/quantmod/tests/test_chartSeries.R
/usr/lib64/R/library/quantmod/tests/test_getSymbols.R
/usr/lib64/R/library/quantmod/tests/tests.R
