#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-quantmod
Version  : 0.4.26
Release  : 75
URL      : https://cran.r-project.org/src/contrib/quantmod_0.4.26.tar.gz
Source0  : https://cran.r-project.org/src/contrib/quantmod_0.4.26.tar.gz
Summary  : Quantitative Financial Modelling Framework
Group    : Development/Tools
License  : GPL-3.0
Requires: R-TTR
Requires: R-curl
Requires: R-jsonlite
Requires: R-xts
Requires: R-zoo
BuildRequires : R-TTR
BuildRequires : R-curl
BuildRequires : R-jsonlite
BuildRequires : R-xts
BuildRequires : R-zoo
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%prep
%setup -q -n quantmod
pushd ..
cp -a quantmod buildavx2
popd
pushd ..
cp -a quantmod buildavx512
popd
pushd ..
cp -a quantmod buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740097429

%install
export SOURCE_DATE_EPOCH=1740097429
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/quantmod/DESCRIPTION
/usr/lib64/R/library/quantmod/INDEX
/usr/lib64/R/library/quantmod/Meta/Rd.rds
/usr/lib64/R/library/quantmod/Meta/demo.rds
/usr/lib64/R/library/quantmod/Meta/features.rds
/usr/lib64/R/library/quantmod/Meta/hsearch.rds
/usr/lib64/R/library/quantmod/Meta/links.rds
/usr/lib64/R/library/quantmod/Meta/nsInfo.rds
/usr/lib64/R/library/quantmod/Meta/package.rds
/usr/lib64/R/library/quantmod/NAMESPACE
/usr/lib64/R/library/quantmod/NEWS.md
/usr/lib64/R/library/quantmod/R/quantmod
/usr/lib64/R/library/quantmod/R/quantmod.rdb
/usr/lib64/R/library/quantmod/R/quantmod.rdx
/usr/lib64/R/library/quantmod/demo/chartSeries.R
/usr/lib64/R/library/quantmod/help/AnIndex
/usr/lib64/R/library/quantmod/help/aliases.rds
/usr/lib64/R/library/quantmod/help/paths.rds
/usr/lib64/R/library/quantmod/help/quantmod.rdb
/usr/lib64/R/library/quantmod/help/quantmod.rdx
/usr/lib64/R/library/quantmod/html/00Index.html
/usr/lib64/R/library/quantmod/html/R.css
/usr/lib64/R/library/quantmod/tests/test_Defaults.R
/usr/lib64/R/library/quantmod/tests/test_getDividends.R
/usr/lib64/R/library/quantmod/tests/test_getSplits.R
/usr/lib64/R/library/quantmod/tests/test_getSymbols.R
/usr/lib64/R/library/quantmod/tests/tests.R
